name: Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/**'

jobs:
  version:
    name: "Check Snowflake CLI version"
    runs-on: ubuntu-latest
    environment: snowflake
    steps:
    
      # Checkout repository in order
      # to access the .toml config 
      # file used by snowflake-cli
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
        
      - name: Build package .zip file
        run: |
          sudo apt-get update && sudo apt-get install zip
          zip -r package.zip package_dir
          
      # Install snowflake cli
      - uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          default-config-file-path: "snowflake-config.toml"
          
      # Push the package to snowflake
      - name: Execute Snowflake CLI command
        env:
          SNOWFLAKE_CONNECTIONS_DEPLOY_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_DEPLOY_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_CONNECTIONS_DEPLOY_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_CONNECTIONS_DEPLOY_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_CONNECTIONS_DEPLOY_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_CONNECTIONS_DEPLOY_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          snow --help
          snow connection test
          snow snowpark package upload -f dist/package.zip -s staging_name --overwrite --role accountadmin
